### ISSUE TITLE
I have FileNotFoundError: [Errno 2] No such file or directory: './dataset/data/l5_g4iqq.tmp'

### ISSUE THREAD

**Issue by ZackPashkin** [tobiassteidle/ML_IDCard_Segmentation#3]
I had  FileNotFoundError: [Errno 2] No such file or directory: './dataset/data/l5_g4iqq.tmp'
until I tryed different version for wget

Solution is wget should be
3.0 version
wget==3.0 in requirement.txt

**Comment by tobiassteidle** [comment]
Thx @ZackPashkin, fixed it.
