### ISSUE TITLE
Model.h5 is not included

### ISSUE THREAD

**Issue by mohamad-qodosi** [tobiassteidle/ML_IDCard_Segmentation#6]
Hi.
I wanted to use your code and do some testing of it and see if it is suitable for my project or not.
but the model file is not included and I was not able to find a link to it anywhere.
can you please send the model file for me so I can test the model without having to train it myself?

thanks a lot btw.

**Comment by tobiassteidle** [comment]
Hi,
sorry i have a new computer and don't have the model.h5 there anymore.
I have implemented this in Pytorch, there is the model included.
https://github.com/tobiassteidle/ML_IDCard_Segmentation_Pytorch
For Tensorflow/Keras I would have to re-train that first as well.

**Comment by mohamad-qodosi** [comment]
Thank you so much.
